# Preprocess_Data_FCNN_MdlBatPwr.py
env_name: env_aitm                                    # tf2.3
seed: !!int 0

# Preprocess_create_datasets
data_path: 02_dataset/Mdl_Pwr_MdlBatPwr/ # Pfad angeben mit allen Einzeldatensätzen
dataset_name: Gesamtdatensatz_20_05_21_unskaliert_test_gaertingen
output_path_gesamtdatensatz: 02_dataset/Mdl_Pwr_MdlBatPwr_test/Gesamtdatensatz
horizon_signal: sample_AitmContnsHorzn_VSlopAFinVectLen.csv
array_len: !!int 200
savedataformat: .csv

# Preprocess: Prepare data for training
# Var 1
gesamt_name: 22_04_21_Gesamtdatensatz_flatten_data
output_directory: Preprocessed_Gesamtdatensatz_Var1_skaliert_Splitted_data_shuffled_gear_zeros_droprows
input_directory: 02_dataset/Mdl_Pwr_MdlBatPwr/Gesamtdatensatz/Variante_1/
save_splitted_dataset: !!bool false
shuffle: !!bool false  # false -> LSTM
check_gear_zeros: !!bool false # drop rows with a zero in the gear
sample_signals: !!int 13
target_signals: !!int 7
one_hot_encodding_on: !!bool false  # bezieht aktuell auf den Gang
samples: samples
targets: ground_truth
X_train: train_samples
X_val: val_samples
X_test: test_samples
y_train: train_targets
y_val: val_targets
y_test: test_targets

# Normierung (Min- und Maxwerte)
normalization_on: !!bool false
normalization:
  feature_range:
    min: !!float 0.001
    max: !!int 1
  target:
    CurBat: # Batteriestrom [A]
      Min: !!float -159.9
      Max: !!float 498.600006
    StEdrv: # Status Edrive
      Min: !!int 0
      Max: !!int 1
    GrSt: # Gang [-]
      Min: !!int 1
      Max: !!int 9
    NEng: # Drehzahl [1/s]
      Min: !!int 0
      Max: !!float 67.5  # Beachte: Drehzahl in 1/s -> entspricht max. 4050 1/min
    VVeh: # Geschwindigkeit [km/h]
      Min: !!int 0
      Max: !!int 190
    TqEng: # Motormoment [Nm]
      Min: !!float -27.5
      Max: !!int 920
    TAry: # Zeitstützstellen [s]
      Min: !!int 0
      Max: !!float 6553.5  # in s
  sample:
    ESOC_SOC: # berechneter Ladezustand der HV-Batterie (%)
      Min: !!float 12.8
      Max: !!float 94.9
    VFinVal: # Geschwindigkeit [km/h]
      Min: !!int 0
      Max: !!int 190
    VSlopAFinVectLen: # Anzahl zukünftiger Ereignisse pro Zeitschritt [-]
      Min: !!int 1
      Max: !!int 200
    CurbWeight: # Fahrzeug-Leergewicht [kg]
      Min: !!int 1660
      Max: !!int 2460
    BMS_Batt_Volt: # Batteriespannung [V]
      Min: !!int 0
      Max: !!float 118.8
    Tm_AmbAirP: # Umgebungsdruck [hPa]
      Min: !!int 939
      Max: !!int 1003
    SlopFinVal: # Steigung [-] -> Prozentual
      Min: !!float -0.098
      Max: !!float 0.138
    Tm_AmbAirTp: # Umgebungstemperatur [°C]
      Min: !!int -4
      Max: !!int 18
    Cod_Diff_Ratio_Calc: # Übersetzung Antriebsachse [-]
      Min: !!float 2.64
      Max: !!float 3.46
    MVeh: # Gesamtfahrzeugmasse [kg]
      Min: !!int 1735
      Max: !!int 2675
    WhlPA_Circumfer: # Radumfang in [m]
      Min: !!float 2.093972
      Max: !!float 2.465921
    AFinVal: # Beschleunigung in [m/s^2]
      Min: !!float -4.899
      Max: !!float 1.648
    VSlopAFinPosn: # Position in [m]
      Min: !!int 0
      Max: !!int 7162

