# Preprocess_Data_FCNN_MdlBatPwr.py
env_name: env_aitm                                    # tf2.3
seed: !!int 0

# working_directory: eh_masterarbeit
input_path: 02_dataset/Kombination_MdlPwr_MdlBatPwr/original_structure/AitmContsHorzn_MdlPwr_MdlBatPwr_Cnstr_BatCnstr_2019-12-20 11_41_53gaertringen_mit_routenfuehrung/used_signals/
horizon_signal: sample_AitmContnsHorzn_VSlopAFinVectLen.csv

# Train_test_Split
test_size: !!float 0.06069  # 500 Testdaten
split_data_path: Preprocessed_data
split_data_names:
  train_samples: !!str train_samples
  train_ground_truth: !!str train_ground_truth
  test_samples: !!str test_samples
  test_ground_truth: !!str test_ground_truth
  data_format: !!str .csv  # .npy
  api: !!str _v3_  # bei sequentiell nur: _, _f_api_

# MinMaxScaler
scaler_path: scaler
scaler_format: .save
scaler_feature_range:
  min: !!float 0.0001
  max: !!float 1 # 0.9999
num_inputs: 810
num_outputs: 600  # 5 für sequenzielles Modell ohne Klassifizierung
# Auswahl des Kanals im Pythonfile Z.214

# Normierung
TqEng: # gaertringen
  Min: !!float-28
  Max: !!float 420